#ifndef ANIMATIE_MONITOR_H_INCLUDED
#define ANIMATIE_MONITOR_H_INCLUDED

void Animatie_Monitor(bool &AnimatieMonitor, int maxx, int maxy)
{
    if(AnimatieMonitor==1)
        {
            switch(Limba)
            {
                case RO:
                    readimagefile("Jpg/Romana/AnimatieMonitor/0.jpg", 0, 0, maxx, maxy);
                    delay(500);
                    readimagefile("Jpg/Romana/AnimatieMonitor/1.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/2.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/3.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/4.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/5.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/6.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/7.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/8.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/9.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/10.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/11.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/12.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/13.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/14.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/15.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/16.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/17.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/18.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Romana/AnimatieMonitor/19.jpg", 0, 0, maxx, maxy);
                    delay(200);
                    readimagefile("Jpg/Romana/AnimatieMonitor/20.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Romana/AnimatieMonitor/21.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Romana/AnimatieMonitor/22.jpg", 0, 0, maxx, maxy);
                    delay(1000);
                    readimagefile("Jpg/Romana/AnimatieMonitor/23.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/24.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/25.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/26.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/27.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/28.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/29.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/30.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/31.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/32.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/33.jpg", 0, 0, maxx, maxy);
                    delay(10);
                    readimagefile("Jpg/Romana/AnimatieMonitor/34.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Romana/AnimatieMonitor/35.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Romana/AnimatieMonitor/36.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Romana/AnimatieMonitor/37.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Romana/AnimatieMonitor/38.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Romana/AnimatieMonitor/39.jpg", 0, 0, maxx, maxy);
                    delay(500);
                    readimagefile("Jpg/Romana/AnimatieMonitor/40.jpg", 0, 0, maxx, maxy);
                    delay(1200);
                    readimagefile("Jpg/Romana/AnimatieMonitor/41.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/1.jpg", 0, 0, maxx, maxy);
                    delay(1000);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/2.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/3.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/4.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/5.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/6.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/7.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/8.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/9.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Romana/AnimatieMonitor/Zoom/11.jpg", 0, 0, maxx, maxy);
                    break;
                case ENG:
                    readimagefile("Jpg/Engleza/AnimatieMonitor/0.jpg", 0, 0, maxx, maxy);
                    delay(500);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/1.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/2.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/3.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/4.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/5.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/6.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/7.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/8.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/9.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/10.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/11.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/12.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/13.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/14.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/15.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/16.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/17.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/18.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/19.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/20.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/21.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/22.jpg", 0, 0, maxx, maxy);
                    delay(200);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/23.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/24.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/25.jpg", 0, 0, maxx, maxy);
                    delay(1000);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/26.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/27.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/28.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/29.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/30.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/31.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/32.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/33.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/34.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/35.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/36.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/37.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/38.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/39.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/40.jpg", 0, 0, maxx, maxy);
                    delay(500);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/41.jpg", 0, 0, maxx, maxy);
                    delay(1200);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/42.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/1.jpg", 0, 0, maxx, maxy);
                    delay(1000);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/2.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/3.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/4.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/5.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/6.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/7.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/8.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/9.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Engleza/AnimatieMonitor/Zoom/11.jpg", 0, 0, maxx, maxy);
                    break;
                case FR:
                    readimagefile("Jpg/Franceza/AnimatieMonitor/0.jpg", 0, 0, maxx, maxy);
                    delay(500);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/1.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/2.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/3.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/4.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/5.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/6.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/7.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/8.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/9.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/10.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/11.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/12.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/13.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/14.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/15.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/16.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/17.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/18.jpg", 0, 0, maxx, maxy);
                    delay(40);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/19.jpg", 0, 0, maxx, maxy);
                    delay(200);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/20.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/21.jpg", 0, 0, maxx, maxy);
                    delay(300);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/22.jpg", 0, 0, maxx, maxy);
                    delay(1000);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/23.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/24.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/25.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/26.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/27.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/28.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/29.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/30.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/31.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/32.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/33.jpg", 0, 0, maxx, maxy);
                    delay(10);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/34.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/35.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/36.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/37.jpg", 0, 0, maxx, maxy);
                    delay(50);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/38.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/39.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/40.jpg", 0, 0, maxx, maxy);
                    delay(150);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/41.jpg", 0, 0, maxx, maxy);
                    delay(1200);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/42.jpg", 0, 0, maxx, maxy);
                    delay(1000);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/2.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/3.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/4.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/5.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/6.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/7.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/8.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/9.jpg", 0, 0, maxx, maxy);
                    readimagefile("Jpg/Franceza/AnimatieMonitor/Zoom/11.jpg", 0, 0, maxx, maxy);
                    break;

            }

            AnimatieMonitor=0;
        }
}

#endif // ANIMATIE_MONITOR_H_INCLUDED
